services:
  automail-app:
    build:
      context: .
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    container_name: automail-app
    ports:
    - 80:80
    links:
    - automail-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Automail and hold onto persistent files like cache and session use this, one or the other.
    - ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - ./logs/:/www/logs
    environment:
    - CONTAINER_NAME=automail-app
    
    - DB_HOST=automail-db
    - DB_NAME=automail
    - DB_USER=automail
    - DB_PASS=automail

    - SITE_URL=http://localhost
    - ADMIN_EMAIL=admin@admin.com
    - ADMIN_PASS=automail
    - ENABLE_SSL_PROXY=FALSE
    - DISPLAY_ERRORS=FALSE
    - TIMEZONE=America/Vancouver
    restart: always

  automail-db:
    image: tiredofit/mariadb
    container_name: automail-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=automail
      - DB_USER=automail
      - DB_PASS=automail

      - CONTAINER_NAME=automail-db
    restart: always

  automail-db-backup:
    container_name: automail-db-backup
    image: tiredofit/db-backup
    links:
     - automail-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=automail-db-backup
      - DB_HOST=automail-db
      - DB_TYPE=mariadb
      - DB_NAME=automail
      - DB_USER=automail
      - DB_PASS=automail
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always
